### ISSUE TITLE
Unicode error

### ISSUE THREAD

**Issue by kdfred** [andr3w321/espn_scraper#1]
I have an error running the example.py:

python example.py 
['nfl', 'ncf', 'mlb', 'nba', 'ncb', 'ncw', 'wnba', 'nhl']
http://www.espn.com/nfl/teams
('nfl', 32)
http://www.espn.com/ncf/teams
('ncf', 254)
http://www.espn.com/mlb/teams
('mlb', 30)
http://www.espn.com/nba/teams
('nba', 30)
http://www.espn.com/ncb/teams
('ncb', 351)
http://www.espn.com/ncw/teams
('ncw', 349)
http://www.espn.com/wnba/teams
('wnba', 12)
http://www.espn.com/nhl/teams
('nhl', 31)
http://www.espn.com/nfl/scoreboard/_/year/2016/seasontype/2/week/1?xhr=1
http://www.espn.com/nfl/scoreboard/_/year/2016/seasontype/1/week/1?xhr=1
Traceback (most recent call last):
  File "example.py", line 17, in <module>
    data = espn.get_url(scoreboard_url, cached_path="cached_json")
  File "/usr/local/lib/python2.7/dist-packages/espn_scraper/__init__.py", line 379, in get_url
    return get_cached_url(url, league, data_type, cached_path)
  File "/usr/local/lib/python2.7/dist-packages/espn_scraper/__init__.py", line 395, in get_cached_url
    json.dump(data, f, ensure_ascii=False, indent=2, sort_keys=True)
  File "/usr/lib/python2.7/json/__init__.py", line 190, in dump
    fp.write(chunk)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 43: ordinal not in range(128)

**Comment by andr3w321** [comment]
Can you try running with python 3? eg `python3 example.py`
